@startuml colocarEjercitoEnPaisPropio


autonumber
Juego -> Jugador: colocarEjercitosEn(cantidadDeEjercitos, unPais)
Jugador -> Pais: colocarEjercitos(cantidadDeEjercitos, unaFicha)
Pais-> Ficha: esIgualA(unaFicha)
Pais <-- Ficha:True
Pais -> Pais: ejercitos += cantidadDeEjercitos


@enduml